name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt install qt5-default
    - name: cmake
      working-directory: /home/runner/work/logicsim/
      run: sudo cmake .
    - name: make
      working-directory: /home/runner/work/logicsim/
      run: sudo make -j4
